import charming as app

app.no_check()
app.full_screen()
# app.arc(0, 0, 0, 0, 'a', 'b')
# app.circle(0, 0, 'c')
# app.ellipse(0, 0, 'c', 'c')
# app.line(0, 0, 'c', 'c')
# app.point('c', 1)
# app.quad(0, 0, 0, 0, 0, 'c', 'c', 0)
# app.rect(0, 0, 0, 'c')
# app.square(0, 0, 'c')
# app.triangle(0, 0, 0, 0,  0, 'c')
# app.ellipse_mode('c')
# app.rect_mode('c')
# app.stroke_weight('c')
# app.begin_shape('c')
# app.bezier_vertex(0, 0, 0, 0, 0, 'c')
# app.curve_vertex(0, 'c')
# app.end_shape('up')
# app.vertex(0, 'c')
# app.open_shape('c', 'c')
# app.bezier(0, 0, 0, 0, 0, 0, 0, 'c')
# app.bezier_point(0, 0, 0, 'c', 1)
# app.bezier_tangent(0, 0, 0, 0, 'c')
# app.curve(0, 0, 0, 0, 0, 0, 0, 'c')
# app.curve_point(0, 0, 0, 0, 'c')
# app.curve_tangent(0, 0, 0, 0, 'c')
# app.curve_tightness('c')
# app.translate(0, 'c')
# app.scale('0')
# app.shear_x('0')
# app.shear_y('0')
# app.image('a', 0, 0, 0, 0)
# app.image_mode('c')
# app.load_image(0)
# app.color_mode(app.RGB)
# app.tint(' ', (1, 0))
# app.text(0, 0, 0)
# app.text_width(0)
# app.text_height(0)
# app.text_size(0.0)
# app.text_font(0)
# app.set_cursor('c', 0)
# app.color_mode(app.RGB)
# app.background('c', (0, 0, ))
# app.fill('c', (0, 0, ))
# app.stroke('c', (0, ))
# c = app.CColor('c', (1,))
# app.lerp_color(c, c, 0.5)
app.run()
